# Generated by Django 5.1.15 on 2026-07-13 04:11

import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(db_column='idempleado', primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(db_column='numerodocumento', max_length=20)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('cargo', models.CharField(max_length=60)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_ingreso', models.DateField(db_column='fechaingreso', default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idcategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'constraints': [models.UniqueConstraint(fields=('nombre',), name='uq_cat_nombre')],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='idcliente', primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PP', 'Pasaporte'), ('TI', 'Tarjeta de identidad')], db_column='tipodocumento', max_length=20, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(db_column='numerodocumento', max_length=20, verbose_name='Número de identificación')),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombres / Razón social')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos / Sigla')),
                ('tipo_cliente', models.CharField(choices=[('NATURAL', 'Persona natural'), ('JURIDICO', 'Persona jurídica')], db_column='tipocliente', max_length=20, verbose_name='Tipo de cliente')),
                ('regimen_tributario', models.CharField(choices=[('RESPONSABLE', 'Responsable de IVA (Ordinario)'), ('NO_RESPONSABLE', 'No responsable de IVA (Simplificado)')], db_column='regimentributario', default='NO_RESPONSABLE', max_length=20, verbose_name='Régimen tributario')),
                ('representante_legal', models.CharField(db_column='representantelegal', max_length=120, verbose_name='Representante legal')),
                ('habeas_data', models.BooleanField(db_column='habeasdata', default=False, verbose_name='Autoriza habeas data (Ley 1581 de 2012)')),
                ('email', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono / Celular')),
                ('ciudad', models.CharField(max_length=80, verbose_name='Ciudad / Municipio')),
                ('direccion_residencia', models.CharField(db_column='direccionresidencia', max_length=200, verbose_name='Dirección de residencia')),
                ('direccion_operativa', models.CharField(blank=True, db_column='direccionoperativa', max_length=200, null=True, verbose_name='Dirección operativa')),
                ('fecha_registro', models.DateField(db_column='fecharegistro', default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'indexes': [models.Index(fields=['numero_documento'], name='idx_cliente_documento')],
                'constraints': [models.UniqueConstraint(fields=('numero_documento',), name='uq_cli_documento'), models.UniqueConstraint(fields=('email',), name='uq_cli_email'), models.CheckConstraint(condition=models.Q(('tipo_documento__in', ['CC', 'CE', 'NIT', 'PP', 'TI'])), name='chk_cli_tipodoc'), models.CheckConstraint(condition=models.Q(('tipo_cliente__in', ['NATURAL', 'JURIDICO'])), name='chk_cli_tipocliente'), models.CheckConstraint(condition=models.Q(('regimen_tributario__in', ['RESPONSABLE', 'NO_RESPONSABLE'])), name='chk_cli_regimen'), models.CheckConstraint(condition=models.Q(models.Q(('tipo_cliente', 'JURIDICO'), _negated=True), ('tipo_documento', 'NIT'), _connector='OR'), name='chk_cli_juridico_nit')],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(db_column='idempresa', primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=20, verbose_name='NIT')),
                ('razon_social', models.CharField(db_column='razonsocial', max_length=150, verbose_name='Razón social')),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=120)),
                ('sitio_web', models.CharField(blank=True, db_column='sitioweb', max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Empresa',
                'db_table': 'empresa',
                'constraints': [models.UniqueConstraint(fields=('nit',), name='uq_emp_nit')],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(db_column='idmarca', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('es_marca_propia', models.BooleanField(db_column='esmarcapropia', default=False, verbose_name='¿Es marca propia?')),
            ],
            options={
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
                'constraints': [models.UniqueConstraint(fields=('nombre',), name='uq_marca_nombre')],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(db_column='idmetodopago', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'db_table': 'metodo_pago',
                'constraints': [models.UniqueConstraint(fields=('nombre',), name='uq_mp_nombre')],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(db_column='idproveedor', primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PP', 'Pasaporte'), ('TI', 'Tarjeta de identidad')], db_column='tipodocumento', default='NIT', max_length=20, verbose_name='Tipo de documento')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT / Documento')),
                ('razon_social', models.CharField(db_column='razonsocial', max_length=150, verbose_name='Razón social')),
                ('rut', models.CharField(max_length=30, verbose_name='Número del RUT')),
                ('regimen_tributario', models.CharField(choices=[('RESPONSABLE', 'Responsable de IVA (Ordinario)'), ('NO_RESPONSABLE', 'No responsable de IVA (Simplificado)')], db_column='regimentributario', default='RESPONSABLE', max_length=20, verbose_name='Régimen tributario')),
                ('representante_legal', models.CharField(db_column='representantelegal', max_length=120, verbose_name='Representante legal')),
                ('habeas_data', models.BooleanField(db_column='habeasdata', default=True, verbose_name='Autoriza habeas data (Ley 1581 de 2012)')),
                ('ciudad', models.CharField(max_length=80, verbose_name='Ciudad / Municipio')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección operativa')),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=120)),
                ('banco', models.CharField(max_length=60)),
                ('tipo_cuenta', models.CharField(choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], db_column='tipocuenta', default='CORRIENTE', max_length=15, verbose_name='Tipo de cuenta')),
                ('numero_cuenta', models.CharField(db_column='numerocuenta', max_length=30, verbose_name='Número de cuenta')),
                ('tipo_proveedor', models.CharField(choices=[('MATERIA_PRIMA', 'Materia prima'), ('PRODUCTO_TERMINADO', 'Producto terminado'), ('EMPAQUES', 'Empaques'), ('ASEO', 'Aseo e insumos'), ('SERVICIOS', 'Servicios')], db_column='tipoproveedor', max_length=25, verbose_name='Tipo de proveedor')),
                ('tiempo_entrega_promedio', models.IntegerField(db_column='tiempoentregapromedio', default=7, verbose_name='Tiempo de entrega promedio (días)')),
                ('condiciones_pago', models.IntegerField(db_column='condicionespago', default=30, verbose_name='Condiciones de pago (días)')),
                ('calificacion', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1 a 5)')),
                ('contacto_comercial', models.CharField(db_column='contactocomercial', max_length=120, verbose_name='Contacto comercial')),
                ('contacto_cartera', models.CharField(db_column='contactocartera', max_length=120, verbose_name='Contacto de cartera / pagos')),
                ('contacto_logistico', models.CharField(db_column='contactologistico', max_length=120, verbose_name='Contacto logístico')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'constraints': [models.UniqueConstraint(fields=('nit',), name='uq_prov_nit'), models.UniqueConstraint(fields=('email',), name='uq_prov_email'), models.CheckConstraint(condition=models.Q(('calificacion__gte', 1), ('calificacion__lte', 5)), name='chk_prov_calificacion'), models.CheckConstraint(condition=models.Q(('tiempo_entrega_promedio__gt', 0)), name='chk_prov_entrega'), models.CheckConstraint(condition=models.Q(('condiciones_pago__gte', 0)), name='chk_prov_pago'), models.CheckConstraint(condition=models.Q(('tipo_cuenta__in', ['AHORROS', 'CORRIENTE'])), name='chk_prov_tipocuenta')],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idproducto', primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(db_column='codigobarras', max_length=30, verbose_name='Código de barras')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(db_column='precioventa', decimal_places=2, max_digits=12, verbose_name='Precio de venta')),
                ('unidad_medida', models.CharField(choices=[('UND', 'Unidad'), ('KG', 'Kilogramo'), ('LT', 'Litro'), ('MT', 'Metro'), ('GR', 'Gramo'), ('ML', 'Mililitro')], db_column='unidadmedida', max_length=20, verbose_name='Unidad de medida')),
                ('categoria_iva', models.CharField(choices=[('GENERAL', 'General (19%)'), ('DIFERENCIAL', 'Diferencial (5%)'), ('EXENTO', 'Exento (0%)'), ('EXCLUIDO', 'Excluido (no causa IVA)')], db_column='categoriaiva', default='GENERAL', max_length=15, verbose_name='Categoría de IVA')),
                ('iva', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='Tarifa de IVA (%)')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar equivale a una eliminación lógica.', verbose_name='Activo')),
                ('categoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='supermercado.categoria')),
                ('marca', models.ForeignKey(db_column='idmarca', on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='supermercado.marca')),
                ('proveedor', models.ForeignKey(db_column='idproveedor', help_text='Obligatorio: el proveedor debe existir previamente.', on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='supermercado.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='ResolucionDian',
            fields=[
                ('id_resolucion', models.AutoField(db_column='idresolucion', primary_key=True, serialize=False)),
                ('numero_resolucion', models.CharField(db_column='numeroresolucion', max_length=30)),
                ('prefijo', models.CharField(max_length=10)),
                ('rango_desde', models.IntegerField(db_column='rangodesde')),
                ('rango_hasta', models.IntegerField(db_column='rangohasta')),
                ('vigencia_desde', models.DateField(db_column='vigenciadesde')),
                ('vigencia_hasta', models.DateField(db_column='vigenciahasta')),
            ],
            options={
                'verbose_name': 'Resolución DIAN',
                'verbose_name_plural': 'Resoluciones DIAN',
                'db_table': 'resolucion_dian',
                'constraints': [models.UniqueConstraint(fields=('numero_resolucion',), name='uq_res_numero'), models.CheckConstraint(condition=models.Q(('rango_hasta__gt', models.F('rango_desde'))), name='chk_res_rango'), models.CheckConstraint(condition=models.Q(('vigencia_hasta__gt', models.F('vigencia_desde'))), name='chk_res_vigencia')],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(db_column='idsede', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=80)),
                ('departamento', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=20)),
                ('horario_apertura', models.TimeField(db_column='horarioapertura', verbose_name='Horario de apertura')),
                ('horario_cierre', models.TimeField(db_column='horariocierre', verbose_name='Horario de cierre')),
            ],
            options={
                'verbose_name_plural': 'Sedes',
                'db_table': 'sede',
                'constraints': [models.UniqueConstraint(fields=('nombre',), name='uq_sede_nombre'), models.CheckConstraint(condition=models.Q(('horario_cierre__gt', models.F('horario_apertura'))), name='chk_sede_horario')],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(db_column='idorden', primary_key=True, serialize=False)),
                ('prefijo', models.CharField(max_length=10)),
                ('numero_factura', models.IntegerField(db_column='numerofactura', verbose_name='Consecutivo DIAN')),
                ('fecha_orden', models.DateTimeField(db_column='fechaorden', verbose_name='Fecha y hora de generación')),
                ('fecha_expedicion', models.DateTimeField(blank=True, db_column='fechaexpedicion', null=True, verbose_name='Fecha y hora de expedición')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo_venta', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'En línea')], db_column='tipoventa', default='PRESENCIAL', max_length=20, verbose_name='Tipo de venta')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('cufe', models.CharField(blank=True, max_length=96, null=True, verbose_name='CUFE')),
                ('cliente', models.ForeignKey(db_column='idcliente', on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes', to='supermercado.cliente')),
                ('empleado', models.ForeignKey(db_column='idempleado', on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes', to='supermercado.empleado')),
                ('metodo_pago', models.ForeignKey(db_column='idmetodopago', on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes', to='supermercado.metodopago')),
                ('resolucion', models.ForeignKey(db_column='idresolucion', on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes', to='supermercado.resoluciondian')),
                ('sede', models.ForeignKey(db_column='idsede', on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes', to='supermercado.sede')),
            ],
            options={
                'verbose_name': 'Factura de venta',
                'verbose_name_plural': 'Facturas de venta',
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(db_column='idinventario', primary_key=True, serialize=False)),
                ('cantidad_disponible', models.IntegerField(db_column='cantidaddisponible', default=0, verbose_name='Inventario actual')),
                ('demanda_diaria', models.DecimalField(db_column='demandadiaria', decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Demanda diaria (unidades/día)')),
                ('stock_minimo', models.IntegerField(db_column='stockminimo', default=5, verbose_name='Stock mínimo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fechaactualizacion')),
                ('producto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.RESTRICT, related_name='inventarios', to='supermercado.producto')),
                ('sede', models.ForeignKey(db_column='idsede', on_delete=django.db.models.deletion.RESTRICT, related_name='inventarios', to='supermercado.sede')),
            ],
            options={
                'verbose_name_plural': 'Inventario',
                'db_table': 'inventario',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='sede',
            field=models.ForeignKey(db_column='idsede', on_delete=django.db.models.deletion.RESTRICT, related_name='empleados', to='supermercado.sede'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(db_column='idcompra', primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(db_column='fechacompra', default=datetime.date.today, verbose_name='Fecha de pedido')),
                ('lugar_entrega', models.CharField(db_column='lugarentrega', max_length=150, verbose_name='Lugar de entrega (bodega)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('proveedor', models.ForeignKey(db_column='idproveedor', on_delete=django.db.models.deletion.RESTRICT, related_name='compras', to='supermercado.proveedor')),
                ('sede', models.ForeignKey(db_column='idsede', on_delete=django.db.models.deletion.RESTRICT, related_name='compras', to='supermercado.sede')),
            ],
            options={
                'verbose_name': 'Orden de pedido',
                'verbose_name_plural': 'Órdenes de pedido',
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='TarjetaAmarilla',
            fields=[
                ('id_tarjeta', models.AutoField(db_column='idtarjeta', primary_key=True, serialize=False)),
                ('numero_tarjeta', models.CharField(db_column='numerotarjeta', max_length=20)),
                ('fecha_emision', models.DateField(db_column='fechaemision', default=datetime.date.today)),
                ('puntos_acumulados', models.IntegerField(db_column='puntosacumulados', default=0)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('BLOQUEADA', 'Bloqueada')], default='ACTIVA', max_length=15)),
                ('cliente', models.ForeignKey(db_column='idcliente', on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='supermercado.cliente')),
            ],
            options={
                'verbose_name': 'Tarjeta Amarilla',
                'verbose_name_plural': 'Tarjetas Amarillas',
                'db_table': 'tarjeta_amarilla',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_detalle_orden', models.AutoField(db_column='iddetalleorden', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(db_column='preciounitario', decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva_porcentaje', models.DecimalField(db_column='ivaporcentaje', decimal_places=2, default=0, max_digits=5, verbose_name='IVA (%)')),
                ('iva_valor', models.DecimalField(db_column='ivavalor', decimal_places=2, default=0, max_digits=14, verbose_name='Valor del IVA')),
                ('orden', models.ForeignKey(db_column='idorden', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='supermercado.orden')),
                ('producto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_orden', to='supermercado.producto')),
            ],
            options={
                'verbose_name': 'Detalle de factura',
                'verbose_name_plural': 'Detalles de factura',
                'db_table': 'detalle_orden',
                'indexes': [models.Index(fields=['producto'], name='idx_detalleorden_producto')],
                'constraints': [models.UniqueConstraint(fields=('orden', 'producto'), name='uq_dord_prod_orden'), models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='chk_dord_cantidad'), models.CheckConstraint(condition=models.Q(('precio_unitario__gt', 0)), name='chk_dord_precio'), models.CheckConstraint(condition=models.Q(('subtotal', django.db.models.expressions.CombinedExpression(models.F('precio_unitario'), '*', models.F('cantidad')))), name='chk_dord_subtotal')],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(db_column='iddetallecompra', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('precio_unitario', models.DecimalField(db_column='preciounitario', decimal_places=2, max_digits=12, verbose_name='Costo unitario')),
                ('compra', models.ForeignKey(db_column='idcompra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='supermercado.compra')),
                ('producto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_compra', to='supermercado.producto')),
            ],
            options={
                'verbose_name': 'Detalle de orden de pedido',
                'verbose_name_plural': 'Detalles de orden de pedido',
                'db_table': 'detalle_compra',
                'constraints': [models.UniqueConstraint(fields=('compra', 'producto'), name='uq_dcomp_prod_comp'), models.CheckConstraint(condition=models.Q(('cantidad__gte', 1), ('cantidad__lte', 500)), name='chk_dcomp_cantidad'), models.CheckConstraint(condition=models.Q(('precio_unitario__gt', 0)), name='chk_dcomp_precio')],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='idx_producto_categoria'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['proveedor'], name='idx_producto_proveedor'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='idx_producto_nombre'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('codigo_barras',), name='uq_prod_barras'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_venta__gt', 0)), name='chk_prod_precio'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('unidad_medida__in', ['UND', 'KG', 'LT', 'MT', 'GR', 'ML'])), name='chk_prod_unidad'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('iva__in', [0, 5, 19])), name='chk_prod_iva'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('categoria_iva', 'GENERAL'), ('iva', 19)), models.Q(('categoria_iva', 'DIFERENCIAL'), ('iva', 5)), models.Q(('categoria_iva', 'EXENTO'), ('iva', 0)), models.Q(('categoria_iva', 'EXCLUIDO'), ('iva', 0)), _connector='OR'), name='chk_prod_iva_categoria'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['fecha_orden'], name='idx_orden_fecha'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['sede'], name='idx_orden_sede'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['cliente'], name='idx_orden_cliente'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['estado'], name='idx_orden_estado'),
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.UniqueConstraint(fields=('prefijo', 'numero_factura'), name='uq_ord_factura'),
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_venta__in', ['PRESENCIAL', 'ONLINE'])), name='chk_ord_tipo'),
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'PAGADA', 'ANULADA'])), name='chk_ord_estado'),
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('iva')))), name='chk_ord_total'),
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('iva__gte', 0)), name='chk_ord_valores'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['sede'], name='idx_inventario_sede'),
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.UniqueConstraint(fields=('producto', 'sede'), name='uq_inv_prod_sede'),
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_disponible__gte', 0)), name='chk_inv_cantidad'),
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='chk_inv_stock_min'),
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.CheckConstraint(condition=models.Q(('demanda_diaria__gt', 0)), name='chk_inv_demanda'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('numero_documento',), name='uq_emp_documento'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.CheckConstraint(condition=models.Q(('salario__gt', 0)), name='chk_emp_salario'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['proveedor'], name='idx_compra_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='chk_comp_total'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'RECIBIDA', 'CANCELADA'])), name='chk_comp_estado'),
        ),
        migrations.AddConstraint(
            model_name='tarjetaamarilla',
            constraint=models.UniqueConstraint(fields=('numero_tarjeta',), name='uq_tar_numero'),
        ),
        migrations.AddConstraint(
            model_name='tarjetaamarilla',
            constraint=models.CheckConstraint(condition=models.Q(('puntos_acumulados__gte', 0)), name='chk_tar_puntos'),
        ),
        migrations.AddConstraint(
            model_name='tarjetaamarilla',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['ACTIVA', 'INACTIVA', 'BLOQUEADA'])), name='chk_tar_estado'),
        ),
    ]
