\restrict gdGusLXOZ1GBrHTDE4ogWpLBYuwt5jwS6PudgJBTDey4Tgu02CQW8vmt1hLdlau
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
CREATE FUNCTION public.fn_compra_recibida() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE d RECORD;
BEGIN
    IF NEW.estado = 'RECIBIDA' AND OLD.estado <> 'RECIBIDA' THEN
        FOR d IN SELECT idProducto, cantidad
                 FROM DETALLE_COMPRA
                 WHERE idCompra = NEW.idCompra
        LOOP
            INSERT INTO INVENTARIO (idProducto, idSede, cantidadDisponible,
                                    demandaDiaria, stockMinimo, fechaActualizacion)
            VALUES (d.idProducto, NEW.idSede, d.cantidad, 1.00, 5, NOW())
            ON CONFLICT (idProducto, idSede) DO UPDATE
                SET cantidadDisponible = INVENTARIO.cantidadDisponible + EXCLUDED.cantidadDisponible,
                    fechaActualizacion = NOW();
        END LOOP;
    END IF;
    RETURN NEW;
END;
$$;
CREATE FUNCTION public.fn_venta_descuenta_stock() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE v_sede INT;
BEGIN
    SELECT idSede INTO v_sede FROM ORDEN WHERE idOrden = NEW.idOrden;
    UPDATE INVENTARIO
       SET cantidadDisponible = GREATEST(cantidadDisponible - NEW.cantidad, 0),
           fechaActualizacion = NOW()
     WHERE idProducto = NEW.idProducto
       AND idSede     = v_sede;
    RETURN NEW;
END;
$$;
SET default_tablespace = '';
SET default_table_access_method = heap;
CREATE TABLE public.categoria (
    idcategoria integer NOT NULL,
    nombre character varying(80) NOT NULL,
    descripcion text
);
ALTER TABLE public.categoria ALTER COLUMN idcategoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_idcategoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.cliente (
    idcliente integer NOT NULL,
    tipodocumento character varying(20) NOT NULL,
    numerodocumento character varying(20) NOT NULL,
    nombres character varying(80) NOT NULL,
    apellidos character varying(80) NOT NULL,
    tipocliente character varying(20) NOT NULL,
    regimentributario character varying(20) NOT NULL,
    representantelegal character varying(120) NOT NULL,
    habeasdata boolean NOT NULL,
    email character varying(120) NOT NULL,
    telefono character varying(20) NOT NULL,
    ciudad character varying(80) NOT NULL,
    direccionresidencia character varying(200) NOT NULL,
    direccionoperativa character varying(200),
    fecharegistro date NOT NULL,
    CONSTRAINT chk_cli_juridico_nit CHECK (((NOT ((tipocliente)::text = 'JURIDICO'::text)) OR ((tipodocumento)::text = 'NIT'::text))),
    CONSTRAINT chk_cli_regimen CHECK (((regimentributario)::text = ANY ((ARRAY['RESPONSABLE'::character varying, 'NO_RESPONSABLE'::character varying])::text[]))),
    CONSTRAINT chk_cli_tipocliente CHECK (((tipocliente)::text = ANY ((ARRAY['NATURAL'::character varying, 'JURIDICO'::character varying])::text[]))),
    CONSTRAINT chk_cli_tipodoc CHECK (((tipodocumento)::text = ANY ((ARRAY['CC'::character varying, 'CE'::character varying, 'NIT'::character varying, 'PP'::character varying, 'TI'::character varying])::text[])))
);
ALTER TABLE public.cliente ALTER COLUMN idcliente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_idcliente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.compra (
    idcompra integer NOT NULL,
    fechacompra date NOT NULL,
    lugarentrega character varying(150) NOT NULL,
    total numeric(14,2) NOT NULL,
    estado character varying(20) NOT NULL,
    idproveedor integer NOT NULL,
    idsede integer NOT NULL,
    CONSTRAINT chk_comp_estado CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'RECIBIDA'::character varying, 'CANCELADA'::character varying])::text[]))),
    CONSTRAINT chk_comp_total CHECK ((total >= (0)::numeric))
);
ALTER TABLE public.compra ALTER COLUMN idcompra ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compra_idcompra_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.detalle_compra (
    iddetallecompra integer NOT NULL,
    cantidad integer NOT NULL,
    preciounitario numeric(12,2) NOT NULL,
    idcompra integer NOT NULL,
    idproducto integer NOT NULL,
    CONSTRAINT chk_dcomp_cantidad CHECK (((cantidad >= 1) AND (cantidad <= 500))),
    CONSTRAINT chk_dcomp_precio CHECK ((preciounitario > (0)::numeric))
);
ALTER TABLE public.detalle_compra ALTER COLUMN iddetallecompra ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_compra_iddetallecompra_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.detalle_orden (
    iddetalleorden integer NOT NULL,
    cantidad integer NOT NULL,
    preciounitario numeric(12,2) NOT NULL,
    subtotal numeric(14,2) NOT NULL,
    ivaporcentaje numeric(5,2) NOT NULL,
    ivavalor numeric(14,2) NOT NULL,
    idorden integer NOT NULL,
    idproducto integer NOT NULL,
    CONSTRAINT chk_dord_cantidad CHECK ((cantidad > 0)),
    CONSTRAINT chk_dord_precio CHECK ((preciounitario > (0)::numeric)),
    CONSTRAINT chk_dord_subtotal CHECK ((subtotal = (preciounitario * (cantidad)::numeric)))
);
ALTER TABLE public.detalle_orden ALTER COLUMN iddetalleorden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_orden_iddetalleorden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.empleado (
    idempleado integer NOT NULL,
    numerodocumento character varying(20) NOT NULL,
    nombres character varying(80) NOT NULL,
    apellidos character varying(80) NOT NULL,
    cargo character varying(60) NOT NULL,
    salario numeric(12,2) NOT NULL,
    fechaingreso date NOT NULL,
    idsede integer NOT NULL,
    CONSTRAINT chk_emp_salario CHECK ((salario > (0)::numeric))
);
ALTER TABLE public.empleado ALTER COLUMN idempleado ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empleado_idempleado_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.empresa (
    idempresa integer NOT NULL,
    nit character varying(20) NOT NULL,
    razonsocial character varying(150) NOT NULL,
    direccion character varying(200) NOT NULL,
    ciudad character varying(80) NOT NULL,
    telefono character varying(20) NOT NULL,
    email character varying(120) NOT NULL,
    sitioweb character varying(120) NOT NULL
);
ALTER TABLE public.empresa ALTER COLUMN idempresa ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresa_idempresa_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.inventario (
    idinventario integer NOT NULL,
    cantidaddisponible integer NOT NULL,
    demandadiaria numeric(10,2) NOT NULL,
    stockminimo integer NOT NULL,
    fechaactualizacion timestamp with time zone NOT NULL,
    idproducto integer NOT NULL,
    idsede integer NOT NULL,
    CONSTRAINT chk_inv_cantidad CHECK ((cantidaddisponible >= 0)),
    CONSTRAINT chk_inv_demanda CHECK ((demandadiaria > (0)::numeric)),
    CONSTRAINT chk_inv_stock_min CHECK ((stockminimo >= 0))
);
ALTER TABLE public.inventario ALTER COLUMN idinventario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_idinventario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.marca (
    idmarca integer NOT NULL,
    nombre character varying(80) NOT NULL,
    esmarcapropia boolean NOT NULL
);
ALTER TABLE public.marca ALTER COLUMN idmarca ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marca_idmarca_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.metodo_pago (
    idmetodopago integer NOT NULL,
    nombre character varying(60) NOT NULL,
    descripcion text
);
ALTER TABLE public.metodo_pago ALTER COLUMN idmetodopago ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metodo_pago_idmetodopago_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.orden (
    idorden integer NOT NULL,
    prefijo character varying(10) NOT NULL,
    numerofactura integer NOT NULL,
    fechaorden timestamp with time zone NOT NULL,
    fechaexpedicion timestamp with time zone,
    subtotal numeric(14,2) NOT NULL,
    iva numeric(14,2) NOT NULL,
    total numeric(14,2) NOT NULL,
    tipoventa character varying(20) NOT NULL,
    estado character varying(20) NOT NULL,
    cufe character varying(96),
    idcliente integer NOT NULL,
    idempleado integer NOT NULL,
    idmetodopago integer NOT NULL,
    idresolucion integer NOT NULL,
    idsede integer NOT NULL,
    CONSTRAINT chk_ord_estado CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'PAGADA'::character varying, 'ANULADA'::character varying])::text[]))),
    CONSTRAINT chk_ord_tipo CHECK (((tipoventa)::text = ANY ((ARRAY['PRESENCIAL'::character varying, 'ONLINE'::character varying])::text[]))),
    CONSTRAINT chk_ord_total CHECK ((total = (subtotal + iva))),
    CONSTRAINT chk_ord_valores CHECK (((subtotal >= (0)::numeric) AND (iva >= (0)::numeric)))
);
ALTER TABLE public.orden ALTER COLUMN idorden ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orden_idorden_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.producto (
    idproducto integer NOT NULL,
    codigobarras character varying(30) NOT NULL,
    nombre character varying(150) NOT NULL,
    descripcion text,
    precioventa numeric(12,2) NOT NULL,
    unidadmedida character varying(20) NOT NULL,
    categoriaiva character varying(15) NOT NULL,
    iva numeric(5,2) NOT NULL,
    activo boolean NOT NULL,
    idcategoria integer NOT NULL,
    idmarca integer NOT NULL,
    idproveedor integer NOT NULL,
    CONSTRAINT chk_prod_iva CHECK ((iva = ANY (ARRAY[(0)::numeric, (5)::numeric, (19)::numeric]))),
    CONSTRAINT chk_prod_iva_categoria CHECK (((((categoriaiva)::text = 'GENERAL'::text) AND (iva = (19)::numeric)) OR (((categoriaiva)::text = 'DIFERENCIAL'::text) AND (iva = (5)::numeric)) OR (((categoriaiva)::text = 'EXENTO'::text) AND (iva = (0)::numeric)) OR (((categoriaiva)::text = 'EXCLUIDO'::text) AND (iva = (0)::numeric)))),
    CONSTRAINT chk_prod_precio CHECK ((precioventa > (0)::numeric)),
    CONSTRAINT chk_prod_unidad CHECK (((unidadmedida)::text = ANY ((ARRAY['UND'::character varying, 'KG'::character varying, 'LT'::character varying, 'MT'::character varying, 'GR'::character varying, 'ML'::character varying])::text[])))
);
ALTER TABLE public.producto ALTER COLUMN idproducto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_idproducto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.proveedor (
    idproveedor integer NOT NULL,
    tipodocumento character varying(20) NOT NULL,
    nit character varying(20) NOT NULL,
    razonsocial character varying(150) NOT NULL,
    rut character varying(30) NOT NULL,
    regimentributario character varying(20) NOT NULL,
    representantelegal character varying(120) NOT NULL,
    habeasdata boolean NOT NULL,
    ciudad character varying(80) NOT NULL,
    direccion character varying(200) NOT NULL,
    telefono character varying(20) NOT NULL,
    email character varying(120) NOT NULL,
    banco character varying(60) NOT NULL,
    tipocuenta character varying(15) NOT NULL,
    numerocuenta character varying(30) NOT NULL,
    tipoproveedor character varying(25) NOT NULL,
    tiempoentregapromedio integer NOT NULL,
    condicionespago integer NOT NULL,
    calificacion integer NOT NULL,
    contactocomercial character varying(120) NOT NULL,
    contactocartera character varying(120) NOT NULL,
    contactologistico character varying(120) NOT NULL,
    CONSTRAINT chk_prov_calificacion CHECK (((calificacion >= 1) AND (calificacion <= 5))),
    CONSTRAINT chk_prov_entrega CHECK ((tiempoentregapromedio > 0)),
    CONSTRAINT chk_prov_pago CHECK ((condicionespago >= 0)),
    CONSTRAINT chk_prov_tipocuenta CHECK (((tipocuenta)::text = ANY ((ARRAY['AHORROS'::character varying, 'CORRIENTE'::character varying])::text[])))
);
ALTER TABLE public.proveedor ALTER COLUMN idproveedor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedor_idproveedor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.resolucion_dian (
    idresolucion integer NOT NULL,
    numeroresolucion character varying(30) NOT NULL,
    prefijo character varying(10) NOT NULL,
    rangodesde integer NOT NULL,
    rangohasta integer NOT NULL,
    vigenciadesde date NOT NULL,
    vigenciahasta date NOT NULL,
    CONSTRAINT chk_res_rango CHECK ((rangohasta > rangodesde)),
    CONSTRAINT chk_res_vigencia CHECK ((vigenciahasta > vigenciadesde))
);
ALTER TABLE public.resolucion_dian ALTER COLUMN idresolucion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resolucion_dian_idresolucion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.sede (
    idsede integer NOT NULL,
    nombre character varying(100) NOT NULL,
    direccion character varying(200) NOT NULL,
    ciudad character varying(80) NOT NULL,
    departamento character varying(80) NOT NULL,
    telefono character varying(20) NOT NULL,
    horarioapertura time without time zone NOT NULL,
    horariocierre time without time zone NOT NULL,
    CONSTRAINT chk_sede_horario CHECK ((horariocierre > horarioapertura))
);
ALTER TABLE public.sede ALTER COLUMN idsede ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sede_idsede_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.tarjeta_amarilla (
    idtarjeta integer NOT NULL,
    numerotarjeta character varying(20) NOT NULL,
    fechaemision date NOT NULL,
    puntosacumulados integer NOT NULL,
    estado character varying(15) NOT NULL,
    idcliente integer NOT NULL,
    CONSTRAINT chk_tar_estado CHECK (((estado)::text = ANY ((ARRAY['ACTIVA'::character varying, 'INACTIVA'::character varying, 'BLOQUEADA'::character varying])::text[]))),
    CONSTRAINT chk_tar_puntos CHECK ((puntosacumulados >= 0))
);
ALTER TABLE public.tarjeta_amarilla ALTER COLUMN idtarjeta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tarjeta_amarilla_idtarjeta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE VIEW public.vw_desempeno_proveedores AS
 SELECT pr.idproveedor,
    pr.razonsocial AS proveedor,
    pr.nit,
    pr.tipoproveedor AS tipo,
    pr.calificacion,
    pr.tiempoentregapromedio AS dias_entrega,
    pr.condicionespago AS dias_pago,
    count(DISTINCT p.idproducto) AS productos_suministrados,
    count(DISTINCT co.idcompra) AS pedidos,
    count(DISTINCT co.idcompra) FILTER (WHERE ((co.estado)::text = 'RECIBIDA'::text)) AS pedidos_recibidos,
    COALESCE(sum(DISTINCT co.total), (0)::numeric) AS monto_comprado
   FROM ((public.proveedor pr
     LEFT JOIN public.producto p ON ((p.idproveedor = pr.idproveedor)))
     LEFT JOIN public.compra co ON ((co.idproveedor = pr.idproveedor)))
  GROUP BY pr.idproveedor, pr.razonsocial, pr.nit, pr.tipoproveedor, pr.calificacion, pr.tiempoentregapromedio, pr.condicionespago;
CREATE VIEW public.vw_dias_stock AS
 SELECT i.idinventario,
    p.idproducto,
    p.nombre AS producto,
    pr.razonsocial AS proveedor,
    pr.tiempoentregapromedio AS dias_entrega_proveedor,
    s.idsede,
    s.nombre AS sede,
    i.cantidaddisponible AS inventario_actual,
    i.demandadiaria AS demanda_diaria,
    round(((i.cantidaddisponible)::numeric / i.demandadiaria), 1) AS dias_stock,
        CASE
            WHEN (i.cantidaddisponible = 0) THEN 'AGOTADO'::text
            WHEN (((i.cantidaddisponible)::numeric / i.demandadiaria) < (5)::numeric) THEN 'CRITICO'::text
            WHEN (((i.cantidaddisponible)::numeric / i.demandadiaria) <= (15)::numeric) THEN 'ALERTA'::text
            ELSE 'SEGURO'::text
        END AS categoria_estado,
        CASE
            WHEN (i.cantidaddisponible = 0) THEN 'Pedido inmediato'::text
            WHEN (((i.cantidaddisponible)::numeric / i.demandadiaria) < (5)::numeric) THEN 'Pedido de emergencia'::text
            WHEN (((i.cantidaddisponible)::numeric / i.demandadiaria) <= (15)::numeric) THEN 'Realizar pedido normal'::text
            ELSE 'Mantener monitoreo'::text
        END AS accion_recomendada
   FROM (((public.inventario i
     JOIN public.producto p ON ((p.idproducto = i.idproducto)))
     JOIN public.proveedor pr ON ((pr.idproveedor = p.idproveedor)))
     JOIN public.sede s ON ((s.idsede = i.idsede)))
  WHERE (p.activo = true);
CREATE VIEW public.vw_ventas_mensuales AS
 SELECT s.idsede,
    s.nombre AS sede,
    s.ciudad,
    (date_trunc('month'::text, o.fechaorden))::date AS mes,
    count(o.idorden) AS facturas,
    sum(o.subtotal) AS base_gravable,
    sum(o.iva) AS iva_recaudado,
    sum(o.total) AS ingresos,
    round(avg(o.total), 0) AS ticket_promedio
   FROM (public.orden o
     JOIN public.sede s ON ((s.idsede = o.idsede)))
  WHERE ((o.estado)::text = 'PAGADA'::text)
  GROUP BY s.idsede, s.nombre, s.ciudad, (date_trunc('month'::text, o.fechaorden));
ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT pk_categoria PRIMARY KEY (idcategoria);
ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT pk_cliente PRIMARY KEY (idcliente);
ALTER TABLE ONLY public.compra
    ADD CONSTRAINT pk_compra PRIMARY KEY (idcompra);
ALTER TABLE ONLY public.detalle_compra
    ADD CONSTRAINT pk_detalle_compra PRIMARY KEY (iddetallecompra);
ALTER TABLE ONLY public.detalle_orden
    ADD CONSTRAINT pk_detalle_orden PRIMARY KEY (iddetalleorden);
ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT pk_empleado PRIMARY KEY (idempleado);
ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT pk_empresa PRIMARY KEY (idempresa);
ALTER TABLE ONLY public.inventario
    ADD CONSTRAINT pk_inventario PRIMARY KEY (idinventario);
ALTER TABLE ONLY public.marca
    ADD CONSTRAINT pk_marca PRIMARY KEY (idmarca);
ALTER TABLE ONLY public.metodo_pago
    ADD CONSTRAINT pk_metodo_pago PRIMARY KEY (idmetodopago);
ALTER TABLE ONLY public.orden
    ADD CONSTRAINT pk_orden PRIMARY KEY (idorden);
ALTER TABLE ONLY public.producto
    ADD CONSTRAINT pk_producto PRIMARY KEY (idproducto);
ALTER TABLE ONLY public.proveedor
    ADD CONSTRAINT pk_proveedor PRIMARY KEY (idproveedor);
ALTER TABLE ONLY public.resolucion_dian
    ADD CONSTRAINT pk_resolucion PRIMARY KEY (idresolucion);
ALTER TABLE ONLY public.sede
    ADD CONSTRAINT pk_sede PRIMARY KEY (idsede);
ALTER TABLE ONLY public.tarjeta_amarilla
    ADD CONSTRAINT pk_tarjeta PRIMARY KEY (idtarjeta);
ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT uq_cat_nombre UNIQUE (nombre);
ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT uq_cli_documento UNIQUE (numerodocumento);
ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT uq_cli_email UNIQUE (email);
ALTER TABLE ONLY public.detalle_compra
    ADD CONSTRAINT uq_dcomp_prod_comp UNIQUE (idcompra, idproducto);
ALTER TABLE ONLY public.detalle_orden
    ADD CONSTRAINT uq_dord_prod_orden UNIQUE (idorden, idproducto);
ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT uq_emp_documento UNIQUE (numerodocumento);
ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT uq_emp_nit UNIQUE (nit);
ALTER TABLE ONLY public.inventario
    ADD CONSTRAINT uq_inv_prod_sede UNIQUE (idproducto, idsede);
ALTER TABLE ONLY public.marca
    ADD CONSTRAINT uq_marca_nombre UNIQUE (nombre);
ALTER TABLE ONLY public.metodo_pago
    ADD CONSTRAINT uq_mp_nombre UNIQUE (nombre);
ALTER TABLE ONLY public.orden
    ADD CONSTRAINT uq_ord_factura UNIQUE (prefijo, numerofactura);
ALTER TABLE ONLY public.producto
    ADD CONSTRAINT uq_prod_barras UNIQUE (codigobarras);
ALTER TABLE ONLY public.proveedor
    ADD CONSTRAINT uq_prov_email UNIQUE (email);
ALTER TABLE ONLY public.proveedor
    ADD CONSTRAINT uq_prov_nit UNIQUE (nit);
ALTER TABLE ONLY public.resolucion_dian
    ADD CONSTRAINT uq_res_numero UNIQUE (numeroresolucion);
ALTER TABLE ONLY public.sede
    ADD CONSTRAINT uq_sede_nombre UNIQUE (nombre);
ALTER TABLE ONLY public.tarjeta_amarilla
    ADD CONSTRAINT uq_tar_numero UNIQUE (numerotarjeta);
CREATE INDEX compra_idproveedor_082957a7 ON public.compra USING btree (idproveedor);
CREATE INDEX compra_idsede_5ac2e23f ON public.compra USING btree (idsede);
CREATE INDEX detalle_compra_idcompra_02ffcb92 ON public.detalle_compra USING btree (idcompra);
CREATE INDEX detalle_compra_idproducto_18e1e354 ON public.detalle_compra USING btree (idproducto);
CREATE INDEX detalle_orden_idorden_90c60b44 ON public.detalle_orden USING btree (idorden);
CREATE INDEX detalle_orden_idproducto_5f8439ba ON public.detalle_orden USING btree (idproducto);
CREATE INDEX empleado_idsede_98a440a2 ON public.empleado USING btree (idsede);
CREATE INDEX idx_cliente_documento ON public.cliente USING btree (numerodocumento);
CREATE INDEX idx_compra_proveedor ON public.compra USING btree (idproveedor);
CREATE INDEX idx_detalleorden_producto ON public.detalle_orden USING btree (idproducto);
CREATE INDEX idx_inventario_sede ON public.inventario USING btree (idsede);
CREATE INDEX idx_orden_cliente ON public.orden USING btree (idcliente);
CREATE INDEX idx_orden_estado ON public.orden USING btree (estado);
CREATE INDEX idx_orden_fecha ON public.orden USING btree (fechaorden);
CREATE INDEX idx_orden_sede ON public.orden USING btree (idsede);
CREATE INDEX idx_producto_categoria ON public.producto USING btree (idcategoria);
CREATE INDEX idx_producto_nombre ON public.producto USING btree (nombre);
CREATE INDEX idx_producto_proveedor ON public.producto USING btree (idproveedor);
CREATE INDEX inventario_idproducto_86409062 ON public.inventario USING btree (idproducto);
CREATE INDEX inventario_idsede_54eeace7 ON public.inventario USING btree (idsede);
CREATE INDEX orden_idcliente_707f3779 ON public.orden USING btree (idcliente);
CREATE INDEX orden_idempleado_e0f4e026 ON public.orden USING btree (idempleado);
CREATE INDEX orden_idmetodopago_78292dd4 ON public.orden USING btree (idmetodopago);
CREATE INDEX orden_idresolucion_a0ffeec4 ON public.orden USING btree (idresolucion);
CREATE INDEX orden_idsede_2d074ffa ON public.orden USING btree (idsede);
CREATE INDEX producto_idcategoria_e3db5816 ON public.producto USING btree (idcategoria);
CREATE INDEX producto_idmarca_39028b60 ON public.producto USING btree (idmarca);
CREATE INDEX producto_idproveedor_fd6033f2 ON public.producto USING btree (idproveedor);
CREATE INDEX tarjeta_amarilla_idcliente_a4a405a5 ON public.tarjeta_amarilla USING btree (idcliente);
CREATE TRIGGER trg_compra_recibida AFTER UPDATE ON public.compra FOR EACH ROW EXECUTE FUNCTION public.fn_compra_recibida();
CREATE TRIGGER trg_venta_descuenta_stock AFTER INSERT ON public.detalle_orden FOR EACH ROW EXECUTE FUNCTION public.fn_venta_descuenta_stock();
ALTER TABLE ONLY public.compra
    ADD CONSTRAINT fk_comp_proveedor FOREIGN KEY (idproveedor) REFERENCES public.proveedor(idproveedor) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.compra
    ADD CONSTRAINT fk_comp_sede FOREIGN KEY (idsede) REFERENCES public.sede(idsede) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.detalle_compra
    ADD CONSTRAINT fk_dcomp_compra FOREIGN KEY (idcompra) REFERENCES public.compra(idcompra) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.detalle_compra
    ADD CONSTRAINT fk_dcomp_producto FOREIGN KEY (idproducto) REFERENCES public.producto(idproducto) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.detalle_orden
    ADD CONSTRAINT fk_dord_orden FOREIGN KEY (idorden) REFERENCES public.orden(idorden) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY public.detalle_orden
    ADD CONSTRAINT fk_dord_producto FOREIGN KEY (idproducto) REFERENCES public.producto(idproducto) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT fk_emp_sede FOREIGN KEY (idsede) REFERENCES public.sede(idsede) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.inventario
    ADD CONSTRAINT fk_inv_producto FOREIGN KEY (idproducto) REFERENCES public.producto(idproducto) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.inventario
    ADD CONSTRAINT fk_inv_sede FOREIGN KEY (idsede) REFERENCES public.sede(idsede) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.orden
    ADD CONSTRAINT fk_ord_cliente FOREIGN KEY (idcliente) REFERENCES public.cliente(idcliente) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.orden
    ADD CONSTRAINT fk_ord_empleado FOREIGN KEY (idempleado) REFERENCES public.empleado(idempleado) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.orden
    ADD CONSTRAINT fk_ord_metodopago FOREIGN KEY (idmetodopago) REFERENCES public.metodo_pago(idmetodopago) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.orden
    ADD CONSTRAINT fk_ord_resolucion FOREIGN KEY (idresolucion) REFERENCES public.resolucion_dian(idresolucion) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.orden
    ADD CONSTRAINT fk_ord_sede FOREIGN KEY (idsede) REFERENCES public.sede(idsede) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fk_prod_categoria FOREIGN KEY (idcategoria) REFERENCES public.categoria(idcategoria) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fk_prod_marca FOREIGN KEY (idmarca) REFERENCES public.marca(idmarca) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fk_prod_proveedor FOREIGN KEY (idproveedor) REFERENCES public.proveedor(idproveedor) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.tarjeta_amarilla
    ADD CONSTRAINT fk_tar_cliente FOREIGN KEY (idcliente) REFERENCES public.cliente(idcliente) ON UPDATE CASCADE ON DELETE CASCADE;
\unrestrict gdGusLXOZ1GBrHTDE4ogWpLBYuwt5jwS6PudgJBTDey4Tgu02CQW8vmt1hLdlau
